using Domain.Exceptions;
using FluentValidation;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System.Net.NetworkInformation;

namespace CoreSecureBoilerPlate.Middleware
{
    public class GlobalExceptionHandler(ILogger<GlobalExceptionHandler> logger) : IExceptionHandler
    {
        public async ValueTask<bool> TryHandleAsync(
            HttpContext httpContext,
            Exception exception,
            CancellationToken cancellationToken)
        {
            //Extract the Correlation ID generated by the custom middleware safely
            var correlationId = httpContext.Response.Headers["X-Correlation-ID"].ToString();

            var problemDetails = new ProblemDetails
            {
                Instance = httpContext.Request.Path
            };

            //Evaluate exception types dynamically and assign proper log levels
            switch (exception)
            {
                case ValidationException validationException:
                    logger.LogWarning("Validation failed for request {Path}. CorrelationID: {CorrelationId}",
                        httpContext.Request.Path, correlationId);

                    problemDetails.Status = StatusCodes.Status400BadRequest;
                    problemDetails.Title = "Invalid input data (Validation Error)";
                    problemDetails.Detail = "Please review the submitted fields.";

                    // Group FluentValidation errors structured by property names
                    var errors = validationException.Errors
                        .GroupBy(e => e.PropertyName)
                        .ToDictionary(g => g.Key, g => g.Select(e => e.ErrorMessage).ToArray());

                    problemDetails.Extensions.Add("errors", errors);
                    break;

                case DomainException domainException:
                    logger.LogWarning(exception, "Domain rule violation caught at {Path}. CorrelationID: {CorrelationId}",
                        httpContext.Request.Path, correlationId);
                    var (statusCode, title) = domainException switch
                    {
                    BusinessRuleViolationException ex when ex.Message.Contains("not exist") =>
                         (StatusCodes.Status404NotFound, "Resource Not Found"),
                        InsufficientFundsException => (StatusCodes.Status400BadRequest, "Insufficient Funds"),
                        OutOfStockException => (StatusCodes.Status400BadRequest, "Out of Stock"),
                        NegativePriceException => (StatusCodes.Status400BadRequest, "Invalid Price Configuration"),
                        CurrencyMismatchException => (StatusCodes.Status400BadRequest, "Currency Conflict"),

                        // أي خطأ دومين آخر لم نقم بجلبه بالتحديد يأخذ هذا العنوان التلقائي
                        _ => (StatusCodes.Status400BadRequest, "Business Rule Violation")
                    };
                    problemDetails.Status = StatusCodes.Status400BadRequest;
                    problemDetails.Title = "Domain Error";
                    problemDetails.Detail = exception.Message;
                    break;

                case UnauthorizedAccessException:
                    logger.LogWarning("Unauthorized access attempt detected at {Path}. CorrelationID: {CorrelationId}",
                        httpContext.Request.Path, correlationId);

                    problemDetails.Status = StatusCodes.Status401Unauthorized;
                    problemDetails.Title = "Unauthorized Access";
                    problemDetails.Detail = "You do not have permission to access this resource.";
                    break;

                case BadHttpRequestException or System.Text.Json.JsonException:
                    logger.LogWarning("Bad request payload received at {Path}. CorrelationID: {CorrelationId}. Error: {Message}",
                        httpContext.Request.Path, correlationId, exception.Message);

                    problemDetails.Status = StatusCodes.Status400BadRequest; 
                    problemDetails.Title = "Bad Request (Invalid Data Format)";
                    problemDetails.Detail = "The provided data format is invalid. Ensure all fields (like GUIDs) are complete and formatted correctly.";
                    break;

                default:
                    // Critical system failure - Log with full stack trace using LogError
                    logger.LogError(exception, "An unhandled critical exception occurred at {Path}. CorrelationID: {CorrelationId}",
                        httpContext.Request.Path, correlationId);

                    problemDetails.Status = StatusCodes.Status500InternalServerError;
                    problemDetails.Title = "Internal Server Error";
                    problemDetails.Type = "https://tools.ietf.org/html/rfc9110#section-15.6.1";
                    problemDetails.Detail = "A critical server error occurred. Please contact system administration with your Correlation ID.";
                    break;
            }

            //Centralized Metadata Pipeline Enrichment
            problemDetails.Extensions.Add("correlationId", correlationId);

            //Uniformly configure response pipeline metadata
            httpContext.Response.StatusCode = problemDetails.Status ?? StatusCodes.Status500InternalServerError;
            httpContext.Response.ContentType = "application/problem+json";

            //Unbiased atomic response write execution
            await httpContext.Response.WriteAsJsonAsync(problemDetails, cancellationToken);

            return true;
        }
    }
}
